In [1]:
import numpy as np 

In [2]:
!pip install numpy

In [3]:
arr = np.array([1, 3, 4])

In [4]:
arr

array([1, 3, 4])

In [5]:
np.zeros((3, 4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [6]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [7]:
np.full((3, 4),1 )

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [8]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [9]:
np.arange(1, 100, 10)

array([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [10]:
myarr = np.array([[1,2,3], [4,5,6], [7,8,9], [10,11,12]])

In [11]:
myarr

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [12]:
myarr.shape

(4, 3)

In [13]:
myarr.size

12

In [14]:
myarr.ndim

2

In [15]:
myarr.dtype

dtype('int32')

In [16]:
myarr = np.array([[1,2,3], [4,5,6], [7,8,9], [10,11,12]], dtype = 'float32')

In [17]:
myarr

array([[ 1.,  2.,  3.],
       [ 4.,  5.,  6.],
       [ 7.,  8.,  9.],
       [10., 11., 12.]], dtype=float32)

In [18]:
n = myarr.astype('float64')

In [19]:
n.dtype

dtype('float64')

In [20]:
myarr.dtype

dtype('float32')

In [21]:
myarr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [11, 12, 13]])

In [22]:
myarr.shape


(4, 3)

In [23]:
reshaped = myarr.reshape((3,4))

In [24]:
reshaped

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 11, 12, 13]])

In [25]:
myarr

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [11, 12, 13]])

In [26]:
myarr.reshape((2,6))

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 11, 12, 13]])

In [27]:
myarr.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 11, 12, 13])