In [1]:
# Py Zip explanation
l1 = [1, 2, 4]
l2 = [6, 7, 8]
list(zip(l1,l2))

[(1, 6), (2, 7), (4, 8)]

In [2]:
# Py list Speed test
import numpy as np
import time 

size = 1_000_000_0

l1 = list(range(size))
l2 = list(range(size))

start = time.time()
add = [x+y for x,y in zip(l1,l2)]
end = time.time()
print(add[0:10])

print(end - start)


[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]
0.752852201461792


In [3]:
# numpy array speedtest
import numpy as np
import time 

size = 1_000_000_0

l1 = np.array(list(range(size)))
l2 = np.array(list(range(size)))

start = time.time()
add = l1 + l2
end = time.time()
print (add[0:10])

print(end - start)

[ 0  2  4  6  8 10 12 14 16 18]
0.13667702674865723


In [4]:
np.array([1,2,3,4,5])

array([1, 2, 3, 4, 5])

In [5]:
arr=np.array([[1,2,3], [4,5,6]])

In [6]:
type(arr)

numpy.ndarray

In [7]:
arr.shape

(2, 3)

In [8]:
import sys
list_data = list(range(1000))
numpy_data = np.array(list_data)
print("Python list size:", sys.getsizeof(list_data) * len(list_data), "bytes")
print("NumPy array size:", numpy_data.nbytes, "bytes")

Python list size: 8056000 bytes
NumPy array size: 4000 bytes


In [9]:
import numpy as np
import time 

size = 1_000_000_0   # 10 million

l1 = list(range(size))

start = time.time()
list_squares = [x ** 2 for x in l1]
end = time.time()

print(list_squares[0:10])
print(end - start)


[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]
0.6783030033111572


In [10]:
import numpy as np
import time 

size = 1_000_000_0   # 10 million

arr1 = np.array(range(size))

start = time.time()
numpy_squares = arr1 ** 2
end = time.time()

print(numpy_squares[0:10])
print(end - start)


[ 0  1  4  9 16 25 36 49 64 81]
0.016115665435791016


# From The cell 9 & 10 we can observe that numpy is Cleaner and Faster!